stages:
  - build jar

build:
  stage: build jar
  tags:
    - maven
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day
  image: maven:3.8.4-openjdk-17